# Generated by Django 4.2.5 on 2024-02-23 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogwebsite', '0003_blog_auther'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='auther',
        ),
    ]
